return {
    s({
        trig = "sst",
        dscr = "Week planning starter",
    },
    {
        t("* *Semana "), i(1, "X"), t("* _ *"), i(2, "14/08"), t(" ~ "),
        i(3, "20/08"), t("*"),
        t({ "", "",
            "* *Segunda-Feira*",
            "** Aulas:",
            "*** Interação Humano-Computador - 17h30 ~ 19h",
            "*** Paradigmas de Programação - 19h30 ~ 21h",
            "* *Terça-Feira*",
            "** Aulas:",
            "*** Introdução à Teoria da Computação - 13h30 ~ 15h",
            "*** Software Básico - 15h30 ~ 17h",
            "* *Quarta-Feira*",
            "** Aulas:",
            "*** Análise de Algoritmos - 13h30 ~ 15h",
            "*** Introdução à Computação Científica - 15h30 ~ 17h",
            "*** Paradigmas de Programação - 17h30 ~ 19h",
            "* *Quinta-Feira*",
            "** Aulas:",
            "*** Introdução à Teoria da Computação - 13h30 ~ 15h",
            "*** Software Básico - 15h30 ~ 17h",
            "*** Interação Humano-Computador - 17h30 ~ 19h",
            "* *Sexta-Feira*",
            "** Aulas:",
            "*** Análise de Algoritmos - 13h30 ~ 15h",
            "*** Introdução à Computação Científica - 15h30 ~ 17h",
            "* *Sábado*",
            "* *Domingo*",
    }),
}),
}
